# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano/nrf52840/zmk
    shield: charybdis_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y "-DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/boards-module"
  - board: xiao_ble//zmk
    shield: charybdis_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y "-DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/boards-module"
  - board: xiao_ble//zmk
    shield: charybdis_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y "-DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/boards-module"

  - board: xiao_ble//zmk
    shield: settings_reset
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset

  - board: nice_nano/nrf52840/zmk
    shield: charybdis_left
    cmake-args: "-DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/boards-module"
  - board: nice_nano/nrf52840/zmk
    shield: charybdis_right
    cmake-args: "-DZMK_EXTRA_MODULES=${GITHUB_WORKSPACE}/boards-module"
